name: Python autotests

on: 
   workflow_dispatch:
      inputs:
         deployment_target:
            description: choose tests set
            required: true
            type: choice
            default: smoke
            options:
               - smoke
               - regression
               - all
   
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Run autotests
        uses: actions/checkout@v4
      
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ' 3.11.1'
      
      - name: Upgrade pip
        run:
          python -m pip install --upgrade pip
      - name: Install dependencies
        run:  
          pip install -r requirements.txt
      
      - name: Run all tests
        if: github.event.inputs.deployment_target == 'all'
        run: pytest --junitxml=report.xml
      
      - name: Run smoke tests
        if: github.event.inputs.deployment_target == 'smoke'
        run: pytest -m smoke --junitxml=report.xml
      
      - name: Run regression tests
        if: github.event.inputs.deployment_target == 'regression'
        run: pytest -m regression --junitxml=report.xml
   
